### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by kimaldis** [willthames/photodeck.lrdevplugin#12]
This version appears to be 0.15 against 0.16.2 downloaded from Photodeck. Any chance we can get the latest version here please.

Many thanks

**Comment by cmaion** [comment]
Justed push to Will's repository the latest changes.

**Comment by kimaldis** [comment]
Issue appears to be with info.lua. If I leave the compiled version of this file in place and copy over the rest Lightroom accepts the plugin

**Comment by kimaldis** [comment]
Found it:

LrToolkitIdentifier = 'com.photodeck.lightroom-publish'

Sorry for the noise

**Comment by cmaion** [comment]
Hi Kim,

Yes, Will's plugin is in a different name space.

Got a word that you have added manual sorting to your repo. Care to share your work?

Cheers

**Comment by kimaldis** [comment]
For sure. Two files need adding to: PhotodeckAPI.lua and PhotoDeckPublishServiceProvider.lua

 PhotodeckAPI.lua:

	function PhotoDeckAPI.imposeSortOrder( urlname, galleryId, remoteIdSequence )
		logger:trace(string.format('PhotoDeckAPI.imposeSortOrder("%s", "%s" )', urlname, galleryId))

		local seq = ""
		for k,v in pairs(remoteIdSequence) do
			logger:trace( string.format( "id: %s", v ))
			if k == 1 then
			seq = v
			else
			seq = seq .. "," .. v
			end
		end

		local galleryInfo = {}
		galleryInfo['gallery[medias_order]'] = seq
		galleryInfo['gallery[content_order]'] = 'manual-first'

		local response, error_msg = PhotoDeckAPI.request('PUT', '/websites/' .. urlname .. '/galleries/' .. galleryId .. '.xml', galleryInfo)

		if error_msg then
			logger:trace( string.format( "PhotoDeckAPI.imposeSortOrder() failed: %s", error_msg ) )
			return false
		end

		return true

	end

and   PhotoDeckPublishServiceProvider.lua:

	publishServiceProvider.supportsCustomSortOrder = true  -- this must be set for ordering
	publishServiceProvider.imposeSortOrderOnPublishedCollection = function( publishSettings, info, remoteIdSequence )

		local urlname = publishSettings.websiteChosen
		local galleryId = info.remoteCollectionId

		return PhotoDeckAPI.imposeSortOrder( urlname, galleryId, remoteIdSequence )

	end

**Comment by cmaion** [comment]
Commit ee6857d5ae84e6f2a2e5af74a230519acfaa98ed, based on your contribution.

Thanks!
