### ISSUE TITLE
Some small fixes/improvments

### ISSUE THREAD

**Issue by cmaion** [willthames/photodeck.lrdevplugin#2]
Hi Will,

Thanks for this plugin and sharing it!

I had a quick look this morning and did some updates to your code while doing so:

1. couple of minor fixes
2. cache some API replies for the duration of the LR session (websites & gallery display styles)
3. don't replace photos with identical file names at upload (this is dangerous for users that don't care about file name uniqueness)
4. start reducing the use of the "full gallery listing" API endpoint, as it can be a bit slow/taxing on huge sites. More needs to be done here ;)
5. fix root gallery discovery when root gallery is not named "Galleries"

My fork is here https://github.com/cmaion/photodeck.lrdevplugin.
Feel free to cherry pick/merge!

Thanks,
Cedric

**Comment by willthames** [comment]
Hi Cedric,
Your changes look pretty good as is. Could you submit it as a pull request and I’ll merge once I’ve had a chance to test the changes.  

Thanks for the improvements,

Will

**Comment by cmaion** [comment]
Hi,

Ok, great!
Here it is: https://github.com/willthames/photodeck.lrdevplugin/pull/3

**Comment by willthames** [comment]
I'll close this issue and will add further comments to #3. Thanks for the PR
