### ISSUE TITLE
Automatically import/sync existing gallery structure? 

### ISSUE THREAD

**Issue by cmaion** [willthames/photodeck.lrdevplugin#4]
Hi Will,

I believe that it would be nice to be able to automatically import/synchronize the existing gallery structure in LR.

New users would probably expect to see their galleries in LR right after having installed and configured the plugin (even if those galleries are shown empty in LR due to lack of reliable mapping of existing photos to the LR catalog -- and if explained in the README file, this may be acceptable), as a confirmation that everything works and is ready for use. This may also clarify how sub-galleries are managed.

Users "on the go" that create galleries from their tablets/phones may also enjoy being able to easily see them right away when they are back to their LR setup.

From what I understand of the code, it seems that we can detect the missing galleries on LR, and, I guess, create them if necessary (and connect them to their PhotoDeck UUID), or delete them if the corresponding PhotoDeck galleries are gone.

What's your opinion on this?

Thanks!

**Comment by willthames** [comment]
Hi Cedric, it's a nice idea and I'm pretty sure you're right, it's almost certainly possible. 

The only trouble I have with it is that I wonder if it would make publishing to an 'empty' gallery and creating a bunch of duplicate images confusing.

My philosophy is that the best way to manage Photodeck galleries that you want to publish through Lightroom is through Lightroom, and that if you do wish to create galleries on the go (and people should definitely want and be able to do that) then it's best to keep maintaining those galleries outside of Lightroom. As soon as you start mixing the two is likely when problems start.

Anyway, those are my thoughts, but I'm definitely open to persuasion. We could always make it an option in the UI.

Will

**Comment by junction10** [comment]
Is it not possible to have the plugin reproduce the gallery structure in Lightroom, and populate it with images it matches in the library to the online site?  The Photoshelter plugin does this.  It finds the image reference (which is also part of the URL) and looks for the matching file in the LR catalogue (I guess it prioritises on RAW files first in case there are matching JPG's in the catalogue)..  then it stores the image ID in the plugin metadata in the LR catalogue, and adds it to the 'gallery' structure in the publishing page of the plugin.

**Comment by willthames** [comment]
@junction10 - once lightroom publishes an image, it knows the remote ID.

As far as I know (and I'm not saying this definitively) there is no way of absolutely tying a photo in Photodeck to its local copy in Lightroom. I don't really know how to even achieve this - particularly if you have a very large Lightroom catalog, you'd have to try and match every photodeck image with the local equivalent (if something in the PhotoDeck results is also in the photo metadata you're in luck). 

Here's the results from a `/medias/uuid.xml` call: 

```
<?xml version="1.0" encoding="UTF-8"?>
<reply>
  <media>
    <uuid>8a2ff171-8fc9-4041-bf9d-cea5fca25fe4</uuid>
    <title>Taala High</title>
    <description nil="true"/>
    <processed>true</processed>
    <location nil="true"/>
    <city nil="true"/>
    <state nil="true"/>
    <country nil="true"/>
    <region nil="true"/>
    <date-created>2012-11-27T07:33:08+10:00</date-created>
    <model-release>false</model-release>
    <property-release>false</property-release>
    <width>427</width>
    <height>640</height>
    <created-at>2014-12-12T23:05:59+10:00</created-at>
    <updated-at>2014-12-28T12:50:22+10:00</updated-at>
    <copyright nil="true"/>
    <type>Image</type>
    <file-name>taalahigh2.jpg</file-name>
    <mime-type>image/jpeg</mime-type>
    <file-size>28284</file-size>
    <keywords>
      <keyword>high</keyword>
      <keyword>Taala</keyword>
    </keywords>
    <pricing-profiles/>
    <galleries>
      <gallery>
        <uuid>91cba0fe-903d-497e-bacb-06702ef4cc80</uuid>
      </gallery>
    </galleries>
    <medias-collections/>
  </media>
  <request>GET /medias/8a2ff171-8fc9-4041-bf9d-cea5fca25fe4.xml</request>
</reply>
```

There is nothing in there (other than filename, which is unreliable - particularly as publishing uses a temporary folder and the filenames will likely get reused every 10000 photos) that can be easily tied to a local image.

If you can identify a local photo being equivalent to a remote photo, then tying the two together seems straightforward (`pubCollection:addPhotoByRemoteId` should do the trick)

However, @cmaion might have some thoughts.

**Comment by cmaion** [comment]
Regarding the gallery structure import/synchronization: I guess we could try to add a "sync" option in the plugin settings, with maybe an explicit warning stating that currently published images in PhotoDeck will not get synchronized back in LR.


And for trying to match currently published images in PhotoDeck with the LR catalog, I don't see any reliable way to do it either (disclaimer: I don't know the LR API!). At best, what might be doable would use some heuristics, like:

1. search the LR catalog for a matching file name, excluding extension (is it easily/cheap do to in LR? no idea!). If we have at least one match:
  * compare the IPTC/XMP "shot at/creation time" field on the PhotoDeck side (date-created), with the corresponding field(s?) within LR matches (is this possible?). E.g., if this field exists on both sides, they should probably somewhat match (within a second or day depending of the available resolutions). Filter out non matching LR matches.
  * if we have one LR match left, assume that we found it (might need to check out how duplicate RAW/TIFF/JPG files for a same source photo are managed in LR though)  
  * if we have multiple LR matches that do not belong to the same RAW/TIFF/JPG photo, we are probably out of luck (not sure that going after IPTC/XMP titles & descriptions would help reducing the LR matches again).

2. make this an option in the settings, as it's would never be 100% reliable! ;)

Not sure at all how feasible this would be!

**Comment by junction10** [comment]
The Photoshelter plugin by PACT software does it really well... I guess it uses file name and capture time... I'll have a look a bit better when I get home 

Sent via iPhone 
M: 07973 618503
www.junction10.net

**Comment by junction10** [comment]
Use a 'scoring' system to import existing files from the library into the collection.

Compare Photodeck image with library image based on:
Filename
Capture Date
Capture Time (Sub Second if possible)
virtual copy status, aspect ratio, title, caption, any other metadata...  If there are multiple files in the catalogue with the same filename (which should be very unlikely if a decent filenaming convention is used), then add points to each image depending on the matches..  highest score is probably the winner..  
For safety, you could probably create a collection with files of multiple matches...

**Comment by cmaion** [comment]
PhotoDeck -> LightRoom gallery structure synchronization implemented in my fork https://github.com/cmaion/photodeck.lrdevplugin (code update is not merged yet in Will's branch).

Feel free to take a look!
There is a push button for that in the plugin's publish settings.

Will look at matching PhotoDeck images with those in the LightRoom catalog in a 2nd step.
