### ISSUE TITLE
Metadata update bugs in current release

### ISSUE THREAD

**Issue by Louie51** [willthames/photodeck.lrdevplugin#9]
I love the new publish plugin. Thanks for all the work to make it happen. I have used it to republish my whole site. In the process I have discovered a couple of minor bugs in the metadata update.

1. Star ratings Lightroom are initially updated to the site but cannot be changed after the initial upload of the image.

2. I have standardized on Headline instead of Title as the short description for each image. So for all my images the IPTC Title field is empty. On initial upload PhotoDeck detects this condition and Uses the IPTC Headline field. However, if I republish an image without the "Re-upload photo" option selected the web site Title field is removed presumably by the empty Title in the updated metadata. I suggest that it should have the same behavior and use the image  Headline field if the Title is empty.

tks, louie

**Comment by cmaion** [comment]
Hi Louis,

Will take look at this in two weeks. Currently enjoying some vacation ;)

Cedric

**Comment by Louie51** [comment]
Hi Cedric,

Thanks for getting back to me and have a great vacation. 

-louie

**Comment by cmaion** [comment]
Ok, IPTC Headline field is now used when title is blank.

Can you update your plugin with [this new version](http://www2.photodeck.com/wp-content/uploads/lightroom/PhotoDeck-lrplugin_0.15.0.zip) and let me know if this solves both points for you?

Thanks,
Cedric

**Comment by Louie51** [comment]
Thanks Cedric,

Just installed and tested and it all works now!

-louie

**Comment by cmaion** [comment]
Ok great!

Closing issue then :)
